server:
  servlet:
    context-path: /api
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: always

spring:
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE